services:
  - type: web
    name: line-bot-notify
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        value: A/plBhKAWC/gFdpWVMyiy2ZHORBcXx8v5xKxsb4zaj6oqyxhJztjhPC4hE1Pb02HWAiXdBkpO5zxsOJcxaflE9QUBe/u8thPplUfg+LCztYFevFp1HppkMoj1Huub1NrfmjAiUesbG+5A429ues85AdB04t89/1O/w1cDnyilFU=
      - key: USER_ID
        value: U15a079bdd4b33504eed31521562b1abc
